[package]
name = "checksum"
version = "0.2.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap", features = [ "yaml" ] }
imprint = { git = "https://github.com/archer884/imprint" }
rayon = "1.5.0"
sha2 = "0.9.3"
walkdir = "2.3.1"
hashbrown = "0.11.0"
md-5 = "0.9.1"
