[package]
name = "checksum"
version = "0.1.2"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33", features = [ "yaml" ] }
imprint = { git = "https://github.com/archer884/imprint" }
rayon = "1.3.0"
sha2 = "0.8.1"
walkdir = "2.3.1"
