[package]
name = "checksum"
version = "0.5.4"
authors = ["J/A <archer884@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = { version = "1.2.0", features = ["traits-preview"] }
clap = { git = "https://github.com/clap-rs/clap", features = ["derive"] }
hashbrown = "0.11.2"
imprint = { git = "https://github.com/archer884/imprint" }
md-5 = "0.10.0"
rayon = "1.5.1"
sha-1 = "0.10.0"
sha2 = "0.10.0"
walkdir = "2.3.2"
